"""initial schema

Revision ID: 3c0758979bae
Revises: 
Create Date: 2026-08-20 10:34:05.244672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0758979bae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'LIVE', 'PAUSED', name='profilestatus', native_enum=False, length=32), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('headline', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('open_to_remote', sa.Boolean(), nullable=False),
    sa.Column('open_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('role_sought', sa.String(length=120), nullable=False),
    sa.Column('role_sought_slug', sa.String(length=60), nullable=True),
    sa.Column('years_prior_experience', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('gap_start', sa.Date(), nullable=False),
    sa.Column('gap_end', sa.Date(), nullable=True),
    sa.Column('gap_months', sa.Integer(), nullable=False),
    sa.Column('gap_reason', sa.Enum('CAREGIVING', 'HEALTH', 'LAYOFF', 'STUDY', 'RELOCATION', 'BUILDING_SOMETHING', 'OTHER', 'PREFER_NOT_TO_SAY', name='gapreason', native_enum=False, length=32), nullable=True),
    sa.Column('gap_activity', sa.Text(), nullable=True),
    sa.Column('expected_ctc', sa.Integer(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('open_to_trial', sa.Boolean(), nullable=False),
    sa.Column('flexibility_note', sa.String(length=200), nullable=True),
    sa.Column('resume_path', sa.String(length=255), nullable=True),
    sa.CheckConstraint('expected_ctc IS NULL OR expected_ctc >= 0', name='ck_ctc_nonneg'),
    sa.CheckConstraint('gap_end IS NULL OR gap_end >= gap_start', name='ck_gap_order'),
    sa.CheckConstraint('notice_period_days >= 0', name='ck_notice_nonneg'),
    sa.CheckConstraint('years_prior_experience >= 0', name='ck_years_nonneg'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_gap_months'), ['gap_months'], unique=False)
        batch_op.create_index('ix_candidate_live', ['status', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_notice_period_days'), ['notice_period_days'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_open_to_remote'), ['open_to_remote'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_open_to_trial'), ['open_to_trial'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_role_sought_slug'), ['role_sought_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidate_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_years_prior_experience'), ['years_prior_experience'], unique=False)

    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=140), nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=False),
    sa.Column('work_email', sa.String(length=160), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employer_work_email'), ['work_email'], unique=True)

    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_slug'), ['slug'], unique=True)

    op.create_table('candidate_tag',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('candidate_id', 'tag_id')
    )
    with op.batch_alter_table('candidate_tag', schema=None) as batch_op:
        batch_op.create_index('ix_candidate_tag_lookup', ['tag_id', 'candidate_id'], unique=False)

    op.create_table('contact_reveal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('revealed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employer_id'], ['employer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_id', 'candidate_id', name='uq_reveal_once')
    )
    with op.batch_alter_table('contact_reveal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_reveal_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_reveal_employer_id'), ['employer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_reveal_revealed_at'), ['revealed_at'], unique=False)
        batch_op.create_index('ix_reveal_quota', ['employer_id', 'revealed_at'], unique=False)

    op.create_table('proof_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=140), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.Enum('CODE', 'WRITING', 'FREELANCE', 'COURSE', 'BUSINESS', 'OTHER', name='proofkind', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proof_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proof_link_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('tag_alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=60), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag_alias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_alias_alias'), ['alias'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag_alias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_alias_alias'))

    op.drop_table('tag_alias')
    with op.batch_alter_table('proof_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proof_link_candidate_id'))

    op.drop_table('proof_link')
    with op.batch_alter_table('contact_reveal', schema=None) as batch_op:
        batch_op.drop_index('ix_reveal_quota')
        batch_op.drop_index(batch_op.f('ix_contact_reveal_revealed_at'))
        batch_op.drop_index(batch_op.f('ix_contact_reveal_employer_id'))
        batch_op.drop_index(batch_op.f('ix_contact_reveal_candidate_id'))

    op.drop_table('contact_reveal')
    with op.batch_alter_table('candidate_tag', schema=None) as batch_op:
        batch_op.drop_index('ix_candidate_tag_lookup')

    op.drop_table('candidate_tag')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_slug'))

    op.drop_table('tag')
    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employer_work_email'))

    op.drop_table('employer')
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_years_prior_experience'))
        batch_op.drop_index(batch_op.f('ix_candidate_updated_at'))
        batch_op.drop_index(batch_op.f('ix_candidate_status'))
        batch_op.drop_index(batch_op.f('ix_candidate_slug'))
        batch_op.drop_index(batch_op.f('ix_candidate_role_sought_slug'))
        batch_op.drop_index(batch_op.f('ix_candidate_open_to_trial'))
        batch_op.drop_index(batch_op.f('ix_candidate_open_to_remote'))
        batch_op.drop_index(batch_op.f('ix_candidate_notice_period_days'))
        batch_op.drop_index('ix_candidate_live')
        batch_op.drop_index(batch_op.f('ix_candidate_gap_months'))
        batch_op.drop_index(batch_op.f('ix_candidate_city'))

    op.drop_table('candidate')
    # ### end Alembic commands ###
